FROM wolnosciowiec/docker-php-app:arm7hf

ENV UAB_TITLE "System monitoring"
ENV UAB_PROVIDERS ""
ENV UAB_CSS "./assets/css/zapatista.css"
ENV UAB_CACHE_ID "uab_"
ENV UAB_CACHE_TTL 60
ENV UAB_CACHE "file"
ENV UAB_REDIS_HOST "localhost"
ENV UAB_REDIS_PORT 6379
ENV UAB_TOR_MANAGEMENT_PORT 9052
ENV UAB_TOR_PASSWORD ""
ENV UAB_PROXY ""
ENV UAB_EXPOSE_URLS 1

ADD . /var/www/html
RUN cd /var/www/html && make deploy
